name: Daily Action - to get latest data (updated monthly)

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Download complete property price data file and remove time
        run: |
          curl -L http://prod.publicdata.landregistry.gov.uk.s3-website-eu-west-1.amazonaws.com/pp-monthly-update-new-version.csv | sed 's/ 00\:00//g' >> pp-monthly-update-new-version.csv
          FIRST_TRANSACTION_ID=$(head -n 1 pp-monthly-update-new-version.csv | cut -d, -f1 | sed 's/^\"\(.*\)\"$/\1/')
          COUNT=$(echo "select count(*) from uk_house_price_data.all_data where transaction_id = '$FIRST_TRANSACTION_ID'" | bq --format=json query | jq .[0].f0_)
          # Have we got an already existing record? If so, stop otherwise upload new data!
          if [ "$COUNT" = "1" ]; then exit 0 fi
          gsutil mv pp-monthly-update-new-version.csv gs://uk-house-price-data/pp-monthly-update-new-version.csv
          bq load ${{ secrets.GCP_PROJECT_ID }}:uk_house_price_data.all_data gs://uk-house-price-data/pp-monthly-update-new-version.csv
