name: Daily Action - to get latest data (updated monthly)

on:
#  workflow_dispatch: # Useful for testing!
  schedule:
    - cron: '30 6 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Download and upload new data if required if needed!
        run: |
          ./daily.sh